name: Nightly Elo retrain

on:
  # 03:10 UTC = 04:10 WAT every day
  schedule:
    - cron: "10 3 * * *"
  workflow_dispatch:   # lets you trigger it manually

jobs:
  retrain:
    runs-on: ubuntu-latest

    permissions:
      contents: write      # so the job can git-push back to main

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0    # needed for pushing later

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install scikit-learn requests tqdm

      - name: Run data pipeline
        run: python data_pipeline.py

      - name: Commit artefacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/elo_ratings.pkl data/matches_clean.csv
          git commit -m "🤖 nightly retrain: `date -u +'%Y-%m-%d'`" || echo "No changes"
          git push origin HEAD:main
